### ISSUE TITLE
I installed as per instruction but it tells me the command is not found

### ISSUE THREAD

**Issue by pxc3113** [pnlng/pdfoutliner#2]
l@l-Lenovo-Rescuer-15ISK:~$ pdfoutliner

Command 'pdfoutliner' not found, did you mean:

  command 'pdfoutline' from deb fntsample (5.3-1build2)

Try: sudo apt install <deb name>

**Comment by ghost** [comment]
Looks a like a `pip` issue. 

Try `pip3 uninstall pdfoutliner && pip3 install pdfoutliner`? 

If it still doesn't work, try `pip3 show pdfoutliner`, and make sure `Location` is in your path. 

<details>
For example, suppose I get 

```
Name: pdfoutliner
Version: 0.0.3
Summary: Command line interface for generating pdftk-style bookmark files in a user-friendly way, and (optionally) outputs a PDF file with the specified outline.
Home-page: https://github.com/GHPen/pdfoutliner
Author: GHPen
Author-email: None
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires:
```

If `/usr/local/lib/python3.6/dist-packages` is not in my `PATH` already, I should add

```
export PATH=$PATH:/usr/local/lib/python3.6/dist-packages
```

to my `~/.profile`, `~/.bashrc`, or equivalent. And then I would restart my terminal. 
</details>
